mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    #post app으로 가는 url 등록
    path('posts/', include('posts.urls')),
]

mysite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', view=views.post_list, name='list'),
    path('create/', view=views.post_create, name='create'),
    path('<int:pk>/update/', view=views.post_update, name='update'),
    path('<int:pk>/delete/', view=views.post_delete, name='delete'),
    path('<int:pk>/detail/', view=views.post_detail, name='detail'),
]

mysite/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    writer = models.CharField(max_length=50)
    content = models.TextField()    #내용을 저장하는 필드, 글자수 제한 없음

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  #admin들어갔을때 쉽게 구분위해 사용
        return self.title


        

mysite/posts/forms.py
from django import forms
from .models import Post
# from mysite.posts import models

class PostForm(forms.ModelForm):
    class Meta:
        model= Post
        fields = '__all__'


        #만드는 순서 url -> view -> 마지막이 템플릿

mysite/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Post
from .forms import PostForm

# Create your views here.
def post_list(request):
    posts = Post.objects.all()  #객체 전부를 담는다
    ctx = {'posts' : posts} #변수 모음
    return render(request, template_name='posts/list.html', context=ctx)

def post_create(request):
    if request.method == 'POST':    #글 작성을 할 때
        form = PostForm(request.POST)   #빈 form이 아니다
        if form.is_valid(): #유효한지
            post = form.save()  #저장
            return redirect('posts:list')   #리다이렉트 한다 list.url로 
    else:   #get방식 = url로 들어갔을때
        form = PostForm()   #빈 form 즉 글을 쓸 양식
        ctx = {'form':form} #creat.html 로 넘겨줌
    return render(request, template_name='posts/create.html', context=ctx)

def post_update(request, pk):
    post = get_object_or_404(Post, id=pk)   #글 목록에서 객체를 하나만 가져온다 즉 post변수에 글 하나를 넣어줌
    #post = Post.objects.get(pk=pk) #이렇게 써도 된다.

    #post방식일 때 : 저장하기 눌렀을 때, 굳이 id가 필요없음 , 즉 데이터 변경할 때 -> 변경이 핵심!
    if request.method=='POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid:
            form.save()
            return redirect('posts:list')

    #get 방식일 때 : 수정버튼 눌러서 들어간 것(링크로 직접 들어간 것), 데이터를 요청할 때만 쓰임 -> 변경이 아님
    else :
        form = PostForm(instance=post) #안에 내용이 있어야 수정한다
        ctx = {'form' : form}

    return render(request, template_name='posts/create.html', context=ctx)

#delete 만들어야 함 (템플릿 노필요)
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('posts:list')

    
    #근데 생각해보니 삭제 버튼 누르면 즉시 지워지니 get만 있으면 될듯??????????

    #post 방식일 때 : 삭제 버튼 눌렀을 때
    #if request.method=='POST':
       # form = PostForm(request.POST, instance=post)
       # if form.is_valid:
       #
    #get 방식일 때 : 삭제 버튼 누른 결과
   # else :
    #    return render(request, template_name='posts/')

   # return render(request, template_name='posts/')

#detail 만들기 인데 템플릿 필요함, 글 상세보기 페이지
def post_detail(request, pk):
    detail = Post.objects.get(pk=pk)   
    return render(request, 'posts/detail.html', {'post': detail }) 

mysite/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        .toolbar{
            background-color: #42FFFF;
            display:flex;
            justify-content: space-around;
        }
    </style>
</head>
<body>
    <div class = toolbar>
        <h1>태현's 게시판</h1>
        <a href="{% url 'posts:create' %}"><button>새 글 작성하기!</button></a>
    </div>
    
</body>
</html>

{% block content %}


{% endblock %}

mysite/posts/templates/posts/create.html
{% extends "posts/base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>포스트 작성</title>
</head>
<body>
    <form action="" method="POST">
        <table>
            {% csrf_token %}
            {{ form.as_table }}
            <!--  view.py에서 받아온 것 -->

            <input type="submit" value="저장하기">  <!--다시 views.py 넘겨줌-->
        </table>
    </form>
</body>
</html>
{% endblock %}

mysite/posts/templates/posts/detail.html
{% extends "posts/base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 상세정보</title>
</head>
<body>
    <form action="" method="POST">
        <table>
            {% csrf_token %}
            <h1>{{ post.title }}</h1><br>
            <p>{{ post.writer }}</p><br>
            <p>{{ post.created_at }}</p><br>
            <p>{{ post.content }}</p><br>
        </table>
    </form>
</body>
</html>
{% endblock %}

mysite/posts/templates/posts/list.html
{% extends 'posts/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for post in posts %}
    <div>제목: {{ post.title }}</div>
    <div>글쓴이: {{ post.writer }}</div>
    <div>내용: {{ post.content }}</div>
    <a href="{% url 'posts:update' post.id %}"><button>수정하기</button></a>
    <a href="{% url 'posts:delete' post.id %}"><button>삭제하기</button></a>
    <a href="{% url 'posts:detail' post.id %}"><button>상세보기</button></a>
    <br>
    {% endfor %}
</body>
</html>
{% endblock %}